trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@4
    inputs:
      mavenPomFile: 'Challenge-OdontoPrev-Java-master/pom.xml'
      goals: 'clean install'
      javaHomeOption: 'Path'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx1024m'
